openapi: 3.0.4
info:
  title: Playdion API
  description: API for the AdrianDevProjects Online Services Playdion.
  version: 2025.5.12

servers:
  - url: https://playdion.adriandevprojects.com/v1
    description: live production server


paths:
  /auth/devicelogin/new/:
    post:
      summary: Starts a new device authorization flow.
      responses:
        "200":
          description: A JSON array with a RequestID & DeviceCode
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    requestid:
                      type: string
                      example: "ABCDEF1234567890"
                    devicecode:
                      type: string
                      example: "123456"

        "500":
          description: Internal server error
          content:
            text/html:
                schema:
                    type: string
                    example: "Something went wrong... please try again"


  /auth/devicelogin/check/:
    post:
      summary: Checks the given device authorization flow for success.
      responses:
        "200":
          description: The device authorization flow was successful.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                      requestid:
                        type: string
                        example: "ABCDEF1234567890"
                      status:
                        type: string
                        example: "SUCCESS"
                      devicecode:
                        type: string
                        example: "123456"

        "100":
          description: The device authorization flow is still pending.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    requestid:
                        type: string
                        example: "ABCDEF1234567890"
                    status:
                        type: string
                        example: "WAITING"
                    devicecode:
                        type: string
                        example: "123456"
        "404":
          description: The device authorization flow is expired.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    requestid:
                        type: string
                        example: "ABCDEF1234567890"
                    status:
                        type: string
                        example: "EXPIRED"

        "500":
            description: Internal server error
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: object
                            properties:
                                requestid:
                                    type: string
                                    example: "ABCDEF1234567890"
                                status:
                                    type: string
                                    example: "UNKNOWN ERROR"
                                devicecode:
                                    type: string
                                    example: "123456"
        "403":
            description: The request to this endpoint was invalid. It contains no RequestID
            content:
                text/html:
                    schema:
                        type: string
                        example: "No RequestID entered"

  /user/get/username/:
      post:
          summary: Gets the username of the given user ID.
          responses:
            "200":
              description: The request was successful and the user exists.
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        username:
                          type: string
                          example: "AdrianDevProjects"

            "404":
              description: The request was successful but the UserID doesn't exist.
              content:
                text/html:
                    schema:
                        type: string
                        example: "This UserID doesn't exist"
            "403":
                description: The request to this endpoint was invalid. It contains no UserID
                content:
                    text/html:
                        schema:
                            type: string
                            example: "No UserID entered"
